name: flutter_tpn
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_login: ^5.0.0
  flutter_split_view: ^0.1.2
  flutter_svg: ^2.0.6
  routemaster: ^1.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  equatable: ^2.0.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
