// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4Gpj80jWOCkIHFaxyuJMKtr5Hz-eWGA',
    appId: '1:1093198369481:web:7da3654640fc23554a3318',
    messagingSenderId: '1093198369481',
    projectId: 'tpnexpo-42b2b',
    authDomain: 'tpnexpo-42b2b.firebaseapp.com',
    storageBucket: 'tpnexpo-42b2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0j0PNxRHEWhQUOq8BP0Q8rMWaZT6S9M',
    appId: '1:1093198369481:android:0618ab417cdb44ad4a3318',
    messagingSenderId: '1093198369481',
    projectId: 'tpnexpo-42b2b',
    storageBucket: 'tpnexpo-42b2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6cQtlIrPKP5rJx4OlrgysPFlQLn0fXA',
    appId: '1:1093198369481:ios:1c944e7586bdae7e4a3318',
    messagingSenderId: '1093198369481',
    projectId: 'tpnexpo-42b2b',
    storageBucket: 'tpnexpo-42b2b.appspot.com',
    iosClientId: '1093198369481-ggb6ucuu7cj2nt1i39o66lhcdg6tqnl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ6cQtlIrPKP5rJx4OlrgysPFlQLn0fXA',
    appId: '1:1093198369481:ios:79566ef0853e14684a3318',
    messagingSenderId: '1093198369481',
    projectId: 'tpnexpo-42b2b',
    storageBucket: 'tpnexpo-42b2b.appspot.com',
    iosClientId: '1093198369481-dc6kaaplnfmfjuhbqdal94ohdp3p8upf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpnFlutter.RunnerTests',
  );
}
