// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdoQppkd33ik4gFyyJ2NAlePjmQiF92Q',
    appId: '1:418524795092:web:367996ed100bc7cde3eb41',
    messagingSenderId: '418524795092',
    projectId: 'fluttertpn',
    authDomain: 'fluttertpn.firebaseapp.com',
    storageBucket: 'fluttertpn.appspot.com',
    measurementId: 'G-LR8V9HJB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmsMv-Kc4-z-nJp1op3r9ji9-EnwqAVI',
    appId: '1:418524795092:android:c446cc409dc787fce3eb41',
    messagingSenderId: '418524795092',
    projectId: 'fluttertpn',
    storageBucket: 'fluttertpn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJGowxSudYBnsW4XP-rMkyNAtmlQEUWQ',
    appId: '1:418524795092:ios:35309e487a8c4969e3eb41',
    messagingSenderId: '418524795092',
    projectId: 'fluttertpn',
    storageBucket: 'fluttertpn.appspot.com',
    iosBundleId: 'com.example.flutterTpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJGowxSudYBnsW4XP-rMkyNAtmlQEUWQ',
    appId: '1:418524795092:ios:fc6cd7dc1fbb9a44e3eb41',
    messagingSenderId: '418524795092',
    projectId: 'fluttertpn',
    storageBucket: 'fluttertpn.appspot.com',
    iosBundleId: 'com.example.flutterTpn.RunnerTests',
  );
}
